<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AcademiaDevExpert.Curso.Data\AcademiaDevExpert.Curso.Data.csproj" />
    <ProjectReference Include="..\AcademiaDevExpert.Curso.Domain\AcademiaDevExpert.Curso.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="automapper" Version="15.1.0" />
  </ItemGroup>

</Project>
