<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AcademiaDevExpert.Financeiro.Business\AcademiaDevExpert.Financeiro.Business.csproj" />
  </ItemGroup>

</Project>
